[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持

;Copy Emoji: https://getemoji.com/

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🤖 AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/AI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=☎ Zoom,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Zoom.list
ruleset=☁ Amazon,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Amazon.list
ruleset=⌨️ 开发,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Developer.list
ruleset=💼 MyOffice,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash//Ruleset/TikTok.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
;ruleset=🎯 全球直连,[]GEOSITE,CN
;ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`fallback`[]🐸 手动切换`[]♻️ 自动选择`[]🕊️ 普通`[]🏡 自建`[]DIRECT`.*`http://www.gstatic.com/generate_204`300,5
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=⌨️ 开发`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=💼 MyOffice`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`.*`[]🎯 全球直连
custom_proxy_group=🎶 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`.*`[]DIRECT`[]REJECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🕊️ 普通`[]🏡 自建`.*`[]DIRECT`[]REJECT
custom_proxy_group=☎ Zoom`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=☁ Amazon`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🏡 自建`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]🕊️ 普通`[]🏡 自建`.*
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]🕊️ 普通`[]🏡 自建`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]🕊️ 普通`[]🏡 自建`.*
custom_proxy_group=🕊️ 普通`url-test`(JMS-387489)`http://www.gstatic.com/generate_204`60,,200
custom_proxy_group=🏡 自建`url-test`(^(?!.*JMS).*)`http://www.gstatic.com/generate_204`300,,200
custom_proxy_group=🏡 自建美国`url-test`(^(?!.*JMS)(?=.*(美|加拿大|US|CA|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|🇨🇦|Canada|United States)))`http://www.gstatic.com/generate_204`300,,200

;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
